### ISSUE TITLE
Ardour5/LV2 - No GUI

### ISSUE THREAD

**Issue by BlueMax** [rncbc/samplv1#13]
Hallo,
when opening the samplv1 gui in Ardour there are no GUI elements. The Ardour plugin host shows up with the Ardour standard top bar elements but the main section (provided by LV2) is empty. The alternative GUI provided by Ardour (generic controls) is more like a "text-only" emergency solution and is not working 100% either. The options 'GEN1 loop start' and 'GEN1 loop end' just sit at the end of all elements without any control or input fields. So even that is not an option atm.

In external 'samplv1-jack' binary the button 'help/configure/use desktop environment native dialogs' doesn't change anything in Ardour.

Neither stdout or any other log shows any evidence of an error (like ppl reported for previous samplv1 versions) and nothing really crashes.

Any idea what's wrong here? Still a qt library mismatch or something?

Is there a documentation for samplv1 anywhere? I have no clue what's 'swap a' and 'swap b' are for or how that 'Add bank/Add programm' feature works. I need 12 different samples and i don't know to set this up (without starting 12 external samplv1 instances).

Arch 4.15.8
XFCE
Ardour v5.12
samplv1 v0.9.0

**Comment by rncbc** [comment]
known issue pertaining to libSUIL 0.10.0 -- the GUI embedding of Qt5 into Gtk2 doesn't work at all (gives you a blank widget).

also, it is really unfortunate that Ardour doesn't give the user a choice, (as qtractor does ;)) because all the v1s do present at least 3 options for its LV2:UI: 1) Qt5UI, 2) external_ui and 3) show/idle interface.

as a workaround you may choose to edit the `samplv1_ui.ttl` file yourself and get rid of the lv2ui:Qt5UI reference, which is to delete the following (4) lines:
```
<http://samplv1.sourceforge.net/lv2#ui>
        a lv2ui:Qt5UI ;
        lv2:requiredFeature <http://lv2plug.in/ns/ext/instance-access> ;
        lv2ui:binary <samplv1_ui.so> .
```
the same should do for all other v1's.
hth.
cheers

**Comment by m4l3z** [comment]
hey @BlueMax 
I have the same issue. I reported it here : http://tracker.ardour.org/view.php?id=7291. 
Workaround : 1) use a container like carla-patchbay to load the plugins. (EH)
2) force host to use extui instead of qt : for each plugin edit /usr/lib/lv2/plugin.lv2/plugin.ttl (ex : /usr/lib/samplv1.lv2/sampl1.ttl) with the right permissions. Locate the right line (starts by "lv2ui:ui" remove the qt part and let the samplv1_ui:ui_external; 

Where did you get ardour from ? Mine is from kxstudio, yes I believe there is a qt mismatch.

**Comment by rncbc** [comment]
as @m4l3z said, thanks, only that the file is located somewhere as LV2_PATH`/samplv1.lv2/sampl1_ui.ttl`, with LV2_PATH being one of `/usr/local/lib/lv2`, `/usr/lib/lv2` or `~/.lv2/`, depending where the lv2 plugin bundle is installed.
byee

**Comment by BlueMax** [comment]
Nice... working fine. :+1: 
Thank you, guys.

My Ardour version is from ~~AUR (Arch User Repository)~~ official Arch repo [(pkgbuild)](https://git.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/ardour) that has been built from [github](https://github.com/ardour/ardour#tag=5.12). It doesn't hold any private libsuil.so. The system lib is libsuil-0.so.0.10.0 indeed.

**Comment by multispa** [comment]
Hello from Spain
I have the same problem with all the v1's plugins
Ardour reports 'failed to instantiate lv2 gui' and any of the workarounds proposed worked for me
Is there any other solution ?
Thanks in advance!

**Comment by rncbc** [comment]
@multispa: is that similar to https://sourceforge.net/p/drumkv1/tickets/15 ? it has been found that the issue is specific to ubuntu 18.04 derivatives and kxstudio repos. especially about the ardour5.12 build from kxstudio and some broken linkage related to harfbuzz and libqt5gui.
