### ISSUE TITLE
Unable to use samplv1 in synthpod after upgrading from 0.9.9 -> 0.9.11

### ISSUE THREAD

**Issue by Spunge** [rncbc/samplv1#28]
I could always use samplv1 in synthpod just fine, but after the last update, synthpod will not load samplv1 reporting:
```
(DSP) [Error] _sp_app_mod_is_supported: <http://samplv1.sourceforge.net/lv2> NOT supported: mixes DSP and UI code in same binary.                                                                                                                                   
(DSP) [Error] _sp_app_mod_add: plugin is not supported                                                                                   
```

I know that i can force synthpod to load samplv1 using the "bad plugins" flag, but it seems to me that samplv1 should not be a "bad plugin"?

**Comment by rncbc** [comment]
better ask what really is the rationale for that in synthpod? since when is having DSP and UI code in same binary a problem?

yes, the v0.9.10 to v0.9.11 move turned out *all* code into the same binary (samplv1.so) but that was actually intended for making it possible to link libQt5Widget *statically* as far to the *self-contained* way that ardour is demanding now, at least on the build systems that are currently prepared to it.

so, just mark it as "bad plugin" in synthpod now that it's willing to be a "good plugin" for ardour.
it's always hard (rather impossible) to please both greeks and trojans at the same time, you know? :)

**Comment by Spunge** [comment]
> so, just mark it as "bad plugin" in synthpod now that it's willing to be a "good plugin" for ardour.

I did not know about this, thanks for the information.
